modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/noobanidus/extracobble/issues"
license="https://github.com/noobanidus/extracobble/blob/master/LICENSE"
[[mods]]
modId="extracobble"
version="${file.jarVersion}"
displayName="Extra Cobble"
displayURL="https://minecraft.curseforge.com/projects/extra-cobble"
authors="Noobanidus"
description='''
Extra cobblestone!
'''
[[dependencies.ExtraCobble]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.ExtraCobble]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,)"
    ordering="NONE"
    side="BOTH"
